# -*- coding: utf-8 -*-
#
# This file is part of Invenio
# Copyright (C) 2015 CERN
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#
# In applying this license, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.


notifications:
  email: false

sudo: false

services:
  - mysql
  - redis

language: python

cache:
  - apt
  - pip

env:
  - REQUIREMENTS=lowest REXTRAS=docs,tests
  - REQUIREMENTS=release REXTRAS=docs,tests
  - REQUIREMENTS=devel REXTRAS=docs,tests

python:
  - "2.7"
  - "3.5"
  - "pypy"

matrix:
  allow_failures:
    - python: pypy
  
before_install:
  - "travis_retry pip install --upgrade pip"
  - "travis_retry pip install check-manifest mock twine wheel coveralls"
  - "python requirements.py --extras=$REXTRAS --level=min > .travis-lowest-requirements.txt"
  - "python requirements.py --extras=$REXTRAS --level=pypi > .travis-release-requirements.txt"
  - "python requirements.py --extras=$REXTRAS --level=dev > .travis-devel-requirements.txt"
  - "mkdir -p ${VIRTUAL_ENV}/var/invenio.base-instance/"
  - "cp .travis.invenio.cfg ${VIRTUAL_ENV}/var/invenio.base-instance/invenio.cfg"

install:
  - "travis_retry pip install -r .travis-$REQUIREMENTS-requirements.txt --allow-all-external"
  - "travis_retry pip install -e .[$REXTRAS]"

before_script:
  - "inveniomanage database init --yes-i-know"
  - "inveniomanage database create --quiet"

script:
  - "check-manifest --ignore .travis-\\*-requirements.txt"
  - "sphinx-build -qnN docs docs/_build/html"
  - "python setup.py test"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: jirikuncar
  password:
    secure: V6OOzYa3q41pDKBLoSYhe14itH0pnDKck3P8agIGQ/2k3hcseTDZg63KCGROChO15ibEQEDEu5qLwUuINesZg3ennS4fNWgMspaCl7+1ZgbW3ROmN9gWD5uJHrsQECF5JCAVRpZUiN+F1zJPDtvOFpSQt968FS4+RUrfFHyxSiY=
  distributions: "compile_catalog sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
